### importing liblaries

In [1]:
import pandas as pd 
import numpy as np 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

## Loading the data using pandas

In [2]:
df = pd.read_csv('car.data')

##### Data Analysis 

In [3]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [4]:
df['buying'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [5]:
df['maint'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [6]:
df['doors'].unique()

array(['2', '3', '4', '5more'], dtype=object)

In [7]:
df['lug_boot'].unique()

array(['small', 'med', 'big'], dtype=object)

In [8]:
df['safety'].unique()

array(['low', 'med', 'high'], dtype=object)

In [9]:
df['class'].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [10]:
X = df[['buying', 'maint', 'safety']].values
y = df[['class']]

In [11]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [12]:
X[:,1]

array(['vhigh', 'vhigh', 'vhigh', ..., 'low', 'low', 'low'], dtype=object)

# By using the label encoder

In [13]:
le = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = le.fit_transform(X[:, i])

In [14]:
X

array([[3, 3, 1],
       [3, 3, 2],
       [3, 3, 0],
       ...,
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 0]], dtype=object)

> Label maping by using dictionary

In [15]:
def enc(input):
    label_maping = {
    'unacc': 0,
    'acc':1,
    'good':2,
    'vgood':3,
    }
    for nat, en in label_maping.items():
        if input in nat:
            return en
    

df['class'] = df['class'].apply(enc)

In [16]:
y = df['class']

## setting up the model parameters

In [17]:
knn = KNeighborsClassifier(n_neighbors=25, weights='uniform')

## spitting in train and test data

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=.33)

## fitting the model 

In [19]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25)

In [20]:
X[0]

array([3, 3, 1], dtype=object)

In [21]:
knn.predict(X_test)
knn.score(X_test, y_test)

0.9211908931698775

In [22]:
knn.predict(X_test[[1]])
print(type(X_test[[1]]))

<class 'numpy.ndarray'>


In [23]:
y_test

1333    0
1514    0
1122    0
106     0
1199    2
       ..
1705    0
1361    0
805     0
796     0
456     0
Name: class, Length: 571, dtype: int64

## Saving the model using the pickle liblary 

In [24]:
import pickle 

In [25]:
with open('/home/aidleroinc/models/knn.pkl', 'wb') as f:
    pickle.dump(knn, f)

In [26]:
with open('/home/aidleroinc/models/knn.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [27]:
loaded_model.predict(X_test[[0]])

array([0])

### The job was done here actually then knn algorithm was used successfull in this project

In [36]:
arr = [[1, 1, 1]]
# arr = np.ndarray(arr)

r = loaded_model.predict(arr)[0]
print(type(r))
z = float(r)
print(type(z))
print(r)

<class 'numpy.int64'>
<class 'float'>
0


In [29]:
loaded_model

KNeighborsClassifier(n_neighbors=25)